# Github Dependabot. Config file
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
      timezone: "Europe/Madrid"
    # Specify labels for `gha` pull requests
    labels:
      - "github-actions"
      - "dependencies"
    commit-message:
      # Prefix all commit messages with `gha`
      # include a list of updated dependencies
      prefix: "gha"
      include: "scope"
    # Allow up to N open pull requests (0 to disable)
    open-pull-requests-limit: 5
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      # for example, `dependabot/github_actions/actions/checkout-2.3.1`
      separator: "/"

  # Mantain dependencies for Go modules
  - package-ecosystem: "gomod"
    # Look for `go.mod` and `lock` files in the `src` directory
    directory: "/src"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
      timezone: "Europe/Madrid"
    # Specify labels for `gomod` pull requests
    labels:
      - "go-modules"
      - "dependencies"
    commit-message:
      # Prefix all commit messages with `gomod`
      # include a list of updated dependencies
      prefix: "gomod"
      include: "scope"
    # Allow up to N open pull requests (0 to disable)
    open-pull-requests-limit: 5
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      # for example, `dependabot/gomod/onsi/ginkgo-2.0.1`
      separator: "/"
